USE mycmsxml;
DELETE FROM Beitrag WHERE SID = 10;
DELETE FROM Beitrag WHERE SID = 11;
DELETE FROM Beitrag WHERE SID = 12;

DELETE FROM Kategorie WHERE CID = 5;
DELETE FROM Kategorie WHERE CID = 6;
DELETE FROM Kategorie WHERE CID = 7;